# Generated by Django 3.2.6 on 2021-08-10 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='liked',
        ),
        migrations.AlterField(
            model_name='news',
            name='author',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='category',
            field=models.CharField(choices=[('general', 'general'), ('business', 'business'), ('entertainment', 'entertainment'), ('health', 'health'), ('science', 'science'), ('sports', 'sports'), ('technology', 'technology')], max_length=20),
        ),
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='published_at',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='news',
            name='url',
            field=models.URLField(null=True),
        ),
    ]
