# Generated by Django 3.2.6 on 2021-08-10 20:04

from django.db import migrations, models
import news_api.models


class Migration(migrations.Migration):

    dependencies = [
        ('news_api', '0002_auto_20210810_1637'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='image',
            new_name='image_url',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='url',
            new_name='link',
        ),
        migrations.RemoveField(
            model_name='news',
            name='author',
        ),
        migrations.RemoveField(
            model_name='news',
            name='category',
        ),
        migrations.RemoveField(
            model_name='news',
            name='country',
        ),
        migrations.RemoveField(
            model_name='news',
            name='language',
        ),
        migrations.RemoveField(
            model_name='news',
            name='published_at',
        ),
        migrations.AddField(
            model_name='news',
            name='content',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='pubDate',
            field=news_api.models.CustomDateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
